// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: productprice.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Eshop.ProductPrice {
  public static partial class IProductPrice
  {
    static readonly string __ServiceName = "Eshop.ProductPrice.IProductPrice";

    static readonly grpc::Marshaller<global::Eshop.ProductPrice.RequestProduct> __Marshaller_RequestProduct = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Eshop.ProductPrice.RequestProduct.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Eshop.ProductPrice.ReturnProduct> __Marshaller_ReturnProduct = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Eshop.ProductPrice.ReturnProduct.Parser.ParseFrom);

    static readonly grpc::Method<global::Eshop.ProductPrice.RequestProduct, global::Eshop.ProductPrice.ReturnProduct> __Method_GetProduceprice = new grpc::Method<global::Eshop.ProductPrice.RequestProduct, global::Eshop.ProductPrice.ReturnProduct>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetProduceprice",
        __Marshaller_RequestProduct,
        __Marshaller_ReturnProduct);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Eshop.ProductPrice.ProductpriceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IProductPrice</summary>
    public abstract partial class IProductPriceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Eshop.ProductPrice.ReturnProduct> GetProduceprice(global::Eshop.ProductPrice.RequestProduct request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IProductPrice</summary>
    public partial class IProductPriceClient : grpc::ClientBase<IProductPriceClient>
    {
      /// <summary>Creates a new client for IProductPrice</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IProductPriceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IProductPrice that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IProductPriceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IProductPriceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IProductPriceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Eshop.ProductPrice.ReturnProduct GetProduceprice(global::Eshop.ProductPrice.RequestProduct request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProduceprice(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Eshop.ProductPrice.ReturnProduct GetProduceprice(global::Eshop.ProductPrice.RequestProduct request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetProduceprice, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Eshop.ProductPrice.ReturnProduct> GetProducepriceAsync(global::Eshop.ProductPrice.RequestProduct request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetProducepriceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Eshop.ProductPrice.ReturnProduct> GetProducepriceAsync(global::Eshop.ProductPrice.RequestProduct request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetProduceprice, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IProductPriceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IProductPriceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IProductPriceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetProduceprice, serviceImpl.GetProduceprice).Build();
    }

  }
}
#endregion
